# Generated by Django 5.2.8 on 2025-12-04 10:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checklist', '0001_initial'),
        ('wagtailcore', '0095_groupsitepermission'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AuditLog',
        ),
        migrations.AddField(
            model_name='checklistitem',
            name='done',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='checklistitem',
            name='page',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='checklist_items', to='wagtailcore.page'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='checklistitem',
            name='title',
            field=models.CharField(default='Default Title', max_length=255),
            preserve_default=False,
        ),
    ]
