# Generated by Django 5.2.8 on 2025-12-04 10:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('checklist', '0002_delete_auditlog_checklistitem_done_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='checklistitem',
            old_name='done',
            new_name='is_done',
        ),
    ]
