# Generated by Django 5.2.8 on 2025-12-04 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checklist', '0003_rename_done_checklistitem_is_done'),
    ]

    operations = [
        migrations.AddField(
            model_name='checklistitem',
            name='description',
            field=models.TextField(blank=True, help_text='Optional description for this checklist item'),
        ),
    ]
